
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/IRACK/AppData/Local/Programs/CLion 2/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/IRACK/AppData/Local/Programs/CLion 2/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/IRACK/AppData/Local/Programs/CLion 2/bin/cmake/win/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
